[build]
  publish = "dist"
  command = "npm run generate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/builds/meta/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/builds/*"
  [headers.values]
    Cache-Control = "public, max-age=1, immutable"

[[headers]]
  for = "/_nuxt/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/_nuxt/builds/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/_nuxt/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_nuxt/assets/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/_nuxt/assets/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/_nuxt/assets/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 