[build]
  command = "npm run generate"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/_nuxt/*.js"
    [headers.values]
    Content-Type = "text/javascript;charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.mjs"
    [headers.values]
    Content-Type = "text/javascript;charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.css"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.woff"
    [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/_nuxt/*.png"
    [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000"

# Статические файлы
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

# Все остальные запросы
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Not = [
    {Path = ["/_nuxt/*"]}
  ]}