[build]
  publish = "dist"
  command = "npm run generate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Content-Type = "font/ttf"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[edge_functions]]
  function = "proxy"
  path = "/.netlify/proxy/_nuxt/*" 