[build]
  publish = "dist"  
  command = "npm run generate"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[edge_functions]]
  function = "ipx"
  path = "/_ipx/*"