[build]
  command = "npm run generate"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/_nuxt/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_nuxt/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_nuxt/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/_nuxt/*.woff"
    [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/_nuxt/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/_nuxt/*.png"
    [headers.values]
    Content-Type = "image/png"

# Сначала обрабатываем статические файлы
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

# Потом все остальное на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200