[build]
  command = "npm run generate"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_nuxt/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_nuxt/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_nuxt/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/_nuxt/*.woff"
    [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/*.woff"
    [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/_nuxt/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"